# Generated by Django 2.2.8 on 2021-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancies', models.CharField(blank=True, max_length=200)),
                ('Glucose', models.CharField(blank=True, max_length=200)),
                ('BloodPressure', models.CharField(blank=True, max_length=200)),
                ('SkinThickness', models.CharField(blank=True, max_length=200)),
                ('Insulin', models.CharField(blank=True, max_length=200)),
                ('BMI', models.CharField(blank=True, max_length=200)),
                ('DiabetesPedigreeFunction', models.CharField(blank=True, max_length=200)),
                ('Age', models.CharField(blank=True, max_length=200)),
                ('Prediction', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
