# Generated by Django 2.2.8 on 2021-03-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
